listen_address: ec2-3-137-140-228.us-east-2.compute.amazonaws.com:8080
cert_file: ./server.crt
key_file: ./server.key

# this section will be used for Token Authorization
api:
  domain: https://localhost
  signing_secret: "your-super-secret"

database:
    addr: 127.0.0.1:3306
    username: ceng316
    password: ceng316
    db_name: dentist_app