listen_address: localhost:8080
cert_file: ./server.crt
key_file: ./server.key

# this section will be used for Token Authorization
api:
  domain: https://localhost
  signing_secret: "your-super-secret"

database:
    addr: 127.0.0.1:3306
    username: root
    password: test
    db_name: license_controller